### ISSUE TITLE
Conversion issues by GCC compiler when using cobs

### ISSUE THREAD

**Issue by nishithpoojary** [cmcqueen/cobs-c#11]
Hi. I have used this cobs file in C programming. But I faced conversion errors.
<img width="494" alt="image" src="https://github.com/cmcqueen/cobs-c/assets/117796593/e209a3d2-7435-47bd-b81c-bdc2b8ea8eaa">

Please let me know how to fix this. Thank you.

**Comment by cmcqueen** [comment]
I don't get these errors with gcc with options `-Wall -Wextra`. But I do get these errors with `-Werror=conversion`.

In this case, I believe these warnings-made-errors are false positives (since the code has been verified with unit testing). But, I could add explicit typecasts to avoid the compiler warnings. Note, typecasts don't make the code more "correct", they just make the warnings go away.

**Comment by nishithpoojary** [comment]
Thank you @cmcqueen . 
The its working after the latest commit.
